accent = "#a39eb8"
cursor = "#dcd7d6"
foreground = "#dcd7d6"
background = "#292323"
selection_foreground = "#dcd7d6"
selection_background = "#a39eb8"

color0 = "#292323"
color1 = "#a48484"
color2 = "#af8a79"
color3 = "#a88373"
color4 = "#a39eb8"
color5 = "#bea7bd"
color6 = "#b0b7c5"
color7 = "#dcd7d6"
color8 = "#877878"
color9 = "#ccb8b8"
color10 = "#be9c8e"
color11 = "#bd9c8f"
color12 = "#d5d2df"
color13 = "#e5dbe5"
color14 = "#e5e7ec"
color15 = "#dcd7d6"
